apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: python:3.11
          workingDir: /code
          command: ["/bin/bash", "-c"]
          args:
            - apt-get update && apt-get install -y curl &&
              curl -L -o /code/index.html https://raw.githubusercontent.com/maravinth10/k8s_Kubernetes/main/stock_market_app/index.html &&
              pip install --no-cache-dir -r /code/requirements.txt &&
              uvicorn main:app --host 0.0.0.0 --port 8000

          ports:
            - containerPort: 8000

          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: app-code
              mountPath: /code/main.py
              subPath: main.py
            - name: app-requirements
              mountPath: /code/requirements.txt
              subPath: requirements.txt

      volumes:
        - name: app-code
          configMap:
            name: fastapi-code
        - name: app-requirements
          configMap:
            name: fastapi-requirements

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
  type: NodePort

