#PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-project
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: pv-postgres-project-claim
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/myname/projects/vehicle-quotes-postgres-data"
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-postgres-project-claim
spec:
  volumeName: pv-postgres-project
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
