apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
          command: ["/bin/bash", "-c"]
          args:
            - pip install -r /app/requirements.txt &&
              uvicorn main:app --host 0.0.0.0 --port 8000
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: app-code
              mountPath: /app/main.py
              subPath: main.py
            - name: app-requirements
              mountPath: /app/requirements.txt
              subPath: requirements.txt
            - name: app-html
              mountPath: /app/index.html
              subPath: index.html    
      volumes:
        - name: app-code
          configMap:
            name: fastapi-code
        - name: app-requirements
          configMap:
            name: fastapi-requirements
        - name: app-html
          configMap:
            name: fastapi-code     
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001

  type: NodePort
